name: ALPENTRAUM
favicon: null
layout_spectrum: 0.4900269864592701
typography_spectrum: 0.2605620492249727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.33273542136885226
  lightness: 0.1055873497389257
  saturation: 0.2750179567374289
  rhythmicContrast: 0.2717380695976317
purpose: []
